apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: my-app-secrets
  namespace: keyvault-demo
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: azure-keyvault
    kind: SecretStore
  target:
    name: my-app-secrets
    creationPolicy: Owner
  data:
    - secretKey: my-secret
      remoteRef:
        key: secret1

    - secretKey: db-password
      remoteRef:
        key: secret2

    - secretKey: DB_USERNAME
      remoteRef:
        key: EXAMPLE-DB-USERNAME

    - secretKey: DB_PASSWORD
      remoteRef:
        key: EXAMPLE-DB-PASSWORD
