---
apiVersion: v1
kind: Pod
metadata:
  name: secret-example
spec:
  containers:
    - name: www
      image: ondrejsika/www
      ports:
        - containerPort: 8000
      env:
        - name: MY_DEFAULT_TOKEN
          value: default
        - name: MY_KEY
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: password
        - name: MY_TOKEN
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: token
        - name: MY_CONFIG
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: config
      volumeMounts:
        - name: secret
          mountPath: /www/password.txt
          subPath: password
        - name: secret
          mountPath: /www/tokenFromString.txt
          subPath: tokenFromString
        - name: config
          mountPath: /www/config.txt
          subPath: config
        - name: config
          mountPath: /www/hello.html
          subPath: hello.html
        - name: config
          mountPath: /www/configmap
      resources:
        requests:
          memory: 10Mi
          cpu: 10m
        limits:
          memory: 20Mi
          cpu: 20m
  volumes:
    - name: config
      configMap:
        name: my-config
    - name: secret
      secret:
        secretName: my-secret
