apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: devel-user-access
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - persistentvolumes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: devel-user-role-binding
  namespace: devel
subjects:
  - kind: ServiceAccount
    name: devel-user
    namespace: devel
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: devel-user-access
