apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-volume-example
spec:
  storageClassName: csi-cephfs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: cephfs-volume-example
  labels:
    app: cephfs-volume-example
spec:
  containers:
    - name: nginx
      image: sikalabs/nginx-public
      resources:
        requests:
          cpu: 20m
          memory: 30Mi
        limits:
          cpu: 50m
          memory: 50Mi
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: cephfs-volume-example
---
apiVersion: v1
kind: Service
metadata:
  name: cephfs-volume-example
spec:
  type: ClusterIP
  selector:
    app: cephfs-volume-example
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
