apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hello-world
  labels:
    app: hello-world-ds
spec:
  selector:
    matchLabels:
      app: hello-world-ds
  template:
    metadata:
      labels:
        app: hello-world-ds
        svc: example
    spec:
      containers:
        - name: hello-world
          image: ghcr.io/ondrejsika/training-example:yellow
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              memory: 20Mi
              cpu: 20m
