apiVersion: v1
kind: ConfigMap
metadata:
  name: expand-config2
data:
  config.yaml.txt: |
    host: postgres
    port: 5432
    user: postgres
    password: $DB_PASSWORD
---
apiVersion: v1
kind: Pod
metadata:
  name: expand-config2
spec:
  volumes:
    - name: config1
      configMap:
        name: expand-config2
    - name: config2
      emptyDir: {}
  initContainers:
    - name: config
      image: sikalabs/slu:v0.22.0
      command:
        - "/bin/sh"
        - "-c"
        - "slu expand file -s /config1/config.yaml.txt > /config2/config.yaml.txt"
      volumeMounts:
        - mountPath: /config1
          name: config1
        - mountPath: /config2
          name: config2
      env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef: 
              name: my-release-postgresql
              key: postgres-password
      resources:
        requests:
          memory: 50Mi
          cpu: 50m
        limits:
          memory: 100Mi
          cpu: 100m
  containers:
    - name: main
      image: sikalabs/nginx-public
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: config2
      resources:
        requests:
          memory: 50Mi
          cpu: 50m
        limits:
          memory: 100Mi
          cpu: 100m
