apiVersion: v1
kind: Pod
metadata:
  name: finite-pod
spec:
  restartPolicy: Never
  containers:
    - name: main
      image: debian:12-slim
      args:
        - "/bin/sh"
        - "-c"
        - "sleep 10"
      resources:
        requests:
          memory: 10Mi
          cpu: 10m
        limits:
          memory: 20Mi
          cpu: 20m
