apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpav2-web
spec:
  selector:
    matchLabels:
      app: hpav2-web
  replicas: 10
  template:
    metadata:
      labels:
        app: hpav2-web
    spec:
      containers:
        - name: app
          image: ondrejsika/go-hello-world:2
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 40m
              memory: 30Mi
            limits:
              cpu: 80m
              memory: 50Mi
---
apiVersion: v1
kind: Service
metadata:
  name: hpa-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: hpav2-web
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpav2
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hpav2-web
  minReplicas: 10
  maxReplicas: 30
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 0
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          averageUtilization: 90
          type: Utilization
