apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: logs
  namespace: logs
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
  - hosts:
    - kibana.k8s.sikademo.com
    secretName: tls-logs
  rules:
    - host: kibana.k8s.sikademo.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: logs-kb-http
                port:
                  number: 5601
