---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-read
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-read
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    resourceNames: ["sleep20s"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-read
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: job-read
subjects:
  - kind: ServiceAccount
    name: job-read
---
apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    svc: example
spec:
  serviceAccountName: job-read
  initContainers:
    - name: wait-for-migrations
      image: sikalabs/slu:v0.23.0
      args:
        - /bin/sh
        - -c
        - slu wait-for k8s job -j sleep20s
  containers:
    - name: main
      image: ondrejsika/go-hello-world:2
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: 10Mi
          cpu: 10m
        limits:
          memory: 100Mi
          cpu: 20m
