apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  labels:
    project: counter
spec:
  serviceName: redis-headless
  selector:
    matchLabels:
      project: counter
      app: redis
  replicas: 3
  template:
    metadata:
      labels:
        project: counter
        app: redis
    spec:
      initContainers:
        - name: wait
          image: busybox:1.28
          command:
            - sleep
          args:
            - "20"
      containers:
        - name: redis
          image: redis
          resources:
            requests:
              cpu: 30m
              memory: 50Mi
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    project: counter
spec:
  ports:
    - port: 6379
  selector:
    project: counter
    app: redis
---
apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  labels:
    project: counter
spec:
  clusterIP: None
  selector:
    project: counter
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter
  labels:
    project: counter
spec:
  selector:
    matchLabels:
      project: counter
      app: counter
  replicas: 2
  template:
    metadata:
      labels:
        project: counter
        app: counter
        svc: example
    spec:
      initContainers:
        - name: init-redis-0
          image: sikalabs/slu:v0.22.0
          args:
            - /bin/sh
            - -c
            - slu wait-for-it -a redis-0.redis-headless:6379
        - name: init-redis-1
          image: sikalabs/slu:v0.22.0
          args:
            - /bin/sh
            - -c
            - slu wait-for-it -a redis-1.redis-headless:6379
        - name: init-redis-2
          image: sikalabs/slu:v0.22.0
          args:
            - /bin/sh
            - -c
            - slu wait-for-it -a redis-2.redis-headless:6379
      containers:
        - name: counter
          image: ondrejsika/counter
          resources:
            requests:
              cpu: 20m
              memory: 10Mi
          env:
            - name: REDIS
              value: redis
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: counter
  labels:
    project: counter
spec:
  type: NodePort
  ports:
    - port: 80
  selector:
    project: counter
    app: counter
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: counter
spec:
  rules:
    - host: counter.127.0.0.1.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: counter
                port:
                  number: 80
