apiVersion: batch/v1
kind: Job
metadata:
  generateName: hello-
spec:
  ttlSecondsAfterFinished: 10
  template:
    metadata:
      name: hello
    spec:
      containers:
        - name: main
          image: debian:12-slim
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo Hello World!
      restartPolicy: Never
