apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  ttlSecondsAfterFinished: 20
  activeDeadlineSeconds: 600
  template:
    metadata:
      name: pi
    spec:
      restartPolicy: Never
      # restartPolicy: OnFailure
      containers:
        - name: main
          image: perl:slim
          command: ["perl"]
          args: ["-Mbignum=bpi", "-wle", "print bpi(1000)"]
