apiVersion: v1
kind: Service
metadata:
  name: hello-world-loadbalancer-internal
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: example
  ports:
    - port: 80
