apiVersion: v1
kind: Pod
metadata:
  name: nodename
spec:
  nodeName: minikube
  containers:
    - name: hello
      image: ghcr.io/ondrejsika/training-example
      resources:
        requests:
          memory: 10Mi
          cpu: 10m
        limits:
          memory: 20Mi
          cpu: 20m
