apiVersion: v1
kind: Pod
metadata:
  name: nodeselector
spec:
  nodeSelector:
    foo: bar
  containers:
    - name: hello
      image: ondrejsika/training-example
      resources:
        requests:
          memory: 10Mi
          cpu: 10m
        limits:
          memory: 20Mi
          cpu: 20m
