apiVersion: batch/v1
kind: Job
metadata:
  name: ab
spec:
  ttlSecondsAfterFinished: 60
  activeDeadlineSeconds: 600
  completions: 20
  parallelism: 4
  template:
    metadata:
      name: ab
    spec:
      restartPolicy: Never
      containers:
        - name: main
          image: sikalabs/dev
          command:
            - /bin/bash
            - -c
            - |
              ab -n 2000 -c 4 http://example/
          resources:
            requests:
              memory: 10Mi
              cpu: 200m
            limits:
              memory: 20Mi
              cpu: 400m
