apiVersion: v1
kind: Pod
metadata:
  name: invalid-yaml
spec:
  containers:
    - name: main
      ports:
        - containerPort: 6379
      resources:
        requests:
          cpu: 50m
          memory: 50Mi
        limits:
          cpu: 100m
          memory: 100Mi
