apiVersion: v1
kind: Pod
metadata:
  name: broken
spec:
  containers:
    - name: main
      image: this-image-does-not-exist
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: 10Mi
          cpu: 10m
        limits:
          memory: 20Gi
          cpu: 20m
