apiVersion: v1
kind: Pod
metadata:
  name: pod-with-low-resources
spec:
  containers:
    - name: main
      image: ghcr.io/ondrejsika/training-example
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: 9Mi
          cpu: 9m
        limits:
          memory: 9Mi
          cpu: 9m
