apiVersion: v1
kind: Pod
metadata:
  name: php
  labels:
    app: php
    svc: example
spec:
  containers:
    - name: php
      image: ondrejsika/php-example-php
      resources:
        requests:
          memory: 50Mi
          cpu: 50m
        limits:
          memory: 100Mi
          cpu: 100m
    - name: nginx
      image: ondrejsika/php-example-nginx
      resources:
        requests:
          memory: 50Mi
          cpu: 50m
        limits:
          memory: 100Mi
          cpu: 100m
