apiVersion: v1
kind: Pod
metadata:
  name: pod-without-service-links
spec:
  enableServiceLinks: false
  restartPolicy: Never
  containers:
    - name: main
      image: busybox
      command: ["env"]
      resources:
        requests:
          memory: 10Mi
          cpu: 10m
        limits:
          memory: 20Mi
          cpu: 20m
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-service-links
spec:
  restartPolicy: Never
  containers:
    - name: main
      image: busybox
      command: ["env"]
      resources:
        requests:
          memory: 10Mi
          cpu: 10m
        limits:
          memory: 20Mi
          cpu: 20m
