apiVersion: v1
kind: Pod
metadata:
  name: private-pod-okd
  labels:
    svc: example-okd
spec:
  imagePullSecrets:
    - name: private-registry-credentials
  containers:
    - name: hello
      image: registry.sikalabs.com/pseudo-private/hello-world-okd
      ports:
        - containerPort: 8000
      resources:
        requests:
          memory: 10Mi
          cpu: 10m
        limits:
          memory: 20Mi
          cpu: 20m
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault

---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: private-registry-credentials
stringData:
  .dockerconfigjson: '{"auths": {"registry.sikalabs.com": {"auth": "cHNldWRvLXByaXZhdGUtdXNlcjphc2RmYXNkZg=="}}}'
