apiVersion: v1
kind: Pod
metadata:
  name: private-pod-harbor
  labels:
    svc: example
spec:
  imagePullSecrets:
    - name: private-pod-harbor-secret
  containers:
    - name: hello
      image: harbor.sl.zone/mpo-example-app/hello-world-server
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: 10Mi
          cpu: 10m
        limits:
          memory: 20Mi
          cpu: 20m
---
apiVersion: v1
kind: Secret
metadata:
  name: private-pod-harbor-secret
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: '{"auths": {"harbor.sl.zone": {"username": "robot$mpo-example-app", "password": "bDcB_PoB8_Q5RW_ix4C"}}}'
