apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-csi-retain
mountOptions:
  - mfsymlinks
  - actimeo=30
  - nosharesock
parameters:
  skuName: Standard_LRS
provisioner: file.csi.azure.com
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
