apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-csi-retained
parameters:
  skuname: StandardSSD_LRS
provisioner: disk.csi.azure.com
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
