apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hello-world
spec:
  replicas: 5
  selector:
    matchLabels:
      app: hello-world-sts
  template:
    metadata:
      labels:
        app: hello-world-sts
        svc: example
    spec:
      containers:
        - name: main
          image: ghcr.io/ondrejsika/training-example:green
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              memory: 20Mi
              cpu: 20m
