apiVersion: apps/v1
kind: Deployment
metadata:
  name: recreate
spec:
  selector:
    matchLabels:
      app: recreate
  replicas: 10
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: recreate
        svc: example
    spec:
      terminationGracePeriodSeconds: 2
      containers:
        - name: hello-world
          image: ghcr.io/ondrejsika/training-example:green
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              memory: 20Mi
              cpu: 20m
---
apiVersion: v1
kind: Service
metadata:
  name: recreate
spec:
  type: NodePort
  selector:
    app: recreate
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
