apiVersion: v1
kind: Service
metadata:
  name: sts8000
spec:
  selector:
    app: sts8000
  ports:
    - port: 80
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: sts8000-headless
spec:
  clusterIP: None
  selector:
    app: sts8000
  # ports:
  #   - port: 80
  #     targetPort: 8000
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts8000
spec:
  serviceName: sts8000-headless
  replicas: 5
  selector:
    matchLabels:
      app: sts8000
  template:
    metadata:
      labels:
        app: sts8000
    spec:
      containers:
        - name: main
          image: ghcr.io/ondrejsika/training-example:v1
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: "8000"
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              memory: 20Mi
              cpu: 20m
