apiVersion: v1
kind: Service
metadata:
  name: {{ include "name" . }}
  labels:
    release: {{ include "name" . }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: http
      targetPort: http
  selector:
    release: {{ include "name" . }}
