apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: dev
  template:
    metadata:
      labels:
        app: dev
    spec:
      containers:
        - name: main
          image: ghcr.io/sikalabs/dev
          command: [sleep, infinity]
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 100m
              memory: 100Mi
